using Microsoft.CodeAnalysis;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Guppy.GUI.Generator
{
    [Generator]
    internal class ImGuiEnumGenerator : ISourceGenerator
    {
        public void Execute(GeneratorExecutionContext context)
        {
            // Find the main method
            var cnamespace = context.Compilation.GlobalNamespace;

            // Build up the source code
            string source = $@"// <auto-generated/>
using System;

namespace {cnamespace}
{{
    public static partial class TestCustomCodeGenerator
    {{
        static partial void HelloFrom(string name) =>
            Console.WriteLine($""Generator says: Hi from '{{name}}'"");
    }}
}}
";
            var typeName = "TestCustomCodeGenerator";

            // Add the source code to the compilation
            context.AddSource($"{typeName}.g.cs", source);
        }

        public void Initialize(GeneratorInitializationContext context)
        {
            if (!Debugger.IsAttached) Debugger.Launch();
        }
    }
}
