using Guppy.GUI.ImGuiNETSourceGenerator.TypeManagers;
using ImGuiNET;
using Microsoft.CodeAnalysis;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Reflection;
using System.Reflection.Metadata;
using System.Text;

namespace Guppy.GUI.ImGuiNETSourceGenerator
{
    [Generator]
    internal class IGuiSourceGenerator : ISourceGenerator
    {
        public void Execute(GeneratorExecutionContext context)
        {
            

            CodeBuilder source = new CodeBuilder();
            source.AppendLine("// <auto-generated/>");
            source.AppendLine();

            using (source.Section($"namespace {context.Compilation.AssemblyName}"))
            {
                using(source.Section("public partial interface IGui"))
                {
                    TypeDecoratorHelper.AddStaticMethodDecorations(typeof(ImGui), source);
                }

                TypeManager.GenerateAllSourceFiles(source);
            }

            context.AddSource($"IGui.g.cs", source.ToString());
        }

        public void Initialize(GeneratorInitializationContext context)
        {
            //Debugger.Launch();
        }
    }
}
