using System;
using System.Text;
using Microsoft.CodeAnalysis;

namespace Guppy.Game.ImGui.Common.ImGuiNETSourceGenerator
{
    public class CodeBuilder : IDisposable
    {
        private readonly StringBuilder _string = new StringBuilder();
        private int _depth = 0;
        private readonly GeneratorExecutionContext _context;
        private readonly string _nameSpace;
        private string _fileName;

        public CodeBuilder(ref GeneratorExecutionContext context, string nameSpace)
        {
            this._context = context;
            this._nameSpace = nameSpace;
        }

        public CodeBuilder File(string filename)
        {
            this._fileName = filename;
            this._string.Clear();

            this.AppendLine("// <auto-generated/>");
            this.AppendLine();

            return this.Section($"namespace {this._nameSpace}");
        }


        public CodeBuilder Section(string section = null)
        {
            if (section != null)
            {
                this.AppendLine(section);
            }

            this.AppendLine("{");
            this._depth++;

            return this;
        }

        public void AppendLine(string line = null)
        {
            if (line == null || line == string.Empty)
            {
                this._string.AppendLine();
                return;
            }

            this._string.Append(new string('\t', this._depth));
            this._string.AppendLine(line);
        }

        public void Dispose()
        {
            this._depth--;
            this.AppendLine("}");

            if (this._depth == 0 && this._fileName != null)
            {
                this._context.AddSource(this._fileName, this._string.ToString());
                this._fileName = null;
            }
        }

        public override string ToString()
        {
            return this._string.ToString();
        }
    }
}